-- =====================================================================
-- Integration Database — 6 bang (muc 7.3 cua De xuat giai phap v2.0)
-- SQL trung tinh, khong dung kieu du lieu rieng cua H2, de co the
-- chuyen sang PostgreSQL chi bang thay doi cau hinh.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. inbox_event — Transactional Inbox + Idempotent Receiver
--    Rang buoc UNIQUE(source_system, event_id) la NEN TANG cua chong trung.
--    Quy tac sinh event_id (muc 5.4):
--      webhook / poller : lay nguyen eventId cua he thong nguon
--      reconciler       : recon:{runId}:{entityType}:{businessKey}
--                         runId sinh MOI moi luot chay — neu dat theo thuc the
--                         thi luot doi soat thu hai se bi chan nham.
-- ---------------------------------------------------------------------
CREATE TABLE inbox_event (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system     VARCHAR(16)  NOT NULL,   -- SIS | LMS | RECON
    event_id          VARCHAR(128) NOT NULL,
    event_type        VARCHAR(64)  NOT NULL,
    business_key      VARCHAR(128),            -- dung de phan luong theo thuc the
    payload           CLOB,                    -- dung lam desiredHint (muc 3.3)
    occurred_at       TIMESTAMP,
    received_at       TIMESTAMP    NOT NULL,
    status            VARCHAR(24)  NOT NULL,   -- RECEIVED PROCESSING DONE RETRYING
                                               -- PENDING_DEPENDENCY DEAD_LETTER
    attempt           INT          NOT NULL DEFAULT 0,
    next_attempt_at   TIMESTAMP,
    worker_id         VARCHAR(64),
    picked_at         TIMESTAMP,
    completed_at      TIMESTAMP,
    last_action       VARCHAR(16),             -- CREATE UPDATE DELETE NOOP
    last_error        VARCHAR(1024),
    CONSTRAINT uk_inbox_source_event UNIQUE (source_system, event_id)
);

CREATE INDEX ix_inbox_status_next  ON inbox_event (status, next_attempt_at);
CREATE INDEX ix_inbox_business_key ON inbox_event (business_key);
CREATE INDEX ix_inbox_received     ON inbox_event (received_at);

-- ---------------------------------------------------------------------
-- 2. id_mapping — BO NHO DEM anh xa ID, KHONG phai nguon su that (BV-4).
--    Khoa noi that la externalRef / externalCode o he thong dich, nen mat
--    ban ghi o day van tra lai duoc — kiem chung boi ca kiem thu I10.
-- ---------------------------------------------------------------------
CREATE TABLE id_mapping (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system  VARCHAR(16)  NOT NULL,   -- he thong so huu source_key
    entity_type    VARCHAR(32)  NOT NULL,   -- STUDENT_USER | SECTION_COURSE
    source_key     VARCHAR(128) NOT NULL,   -- studentId / sectionId
    target_id      VARCHAR(128) NOT NULL,   -- id noi bo cua LMS
    updated_at     TIMESTAMP    NOT NULL,
    CONSTRAINT uk_mapping UNIQUE (source_system, entity_type, source_key)
);

-- ---------------------------------------------------------------------
-- 3. alert_dedup — INT-08, chong doi canh bao hoc tap trung lap
-- ---------------------------------------------------------------------
CREATE TABLE alert_dedup (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  VARCHAR(64)  NOT NULL,
    section_id  VARCHAR(64)  NOT NULL,
    risk_type   VARCHAR(32)  NOT NULL,
    open_flag   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_alert_open UNIQUE (student_id, section_id, risk_type, open_flag)
);

-- ---------------------------------------------------------------------
-- 4. poll_checkpoint — moc thoi gian da doc den cua moi he thong (muc 6.3)
-- ---------------------------------------------------------------------
CREATE TABLE poll_checkpoint (
    source_system  VARCHAR(16) PRIMARY KEY,
    last_event_at  TIMESTAMP,
    updated_at     TIMESTAMP   NOT NULL
);

-- ---------------------------------------------------------------------
-- 5. integration_log — nhat ky kiem toan (NFR-04).
--    event_id dong vai tro MA TUONG QUAN xuyen suot vong doi.
--    TUYET DOI khong luu token hay client secret o bang nay.
-- ---------------------------------------------------------------------
CREATE TABLE integration_log (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       VARCHAR(128),
    event_type     VARCHAR(64),
    source_system  VARCHAR(16),
    handler        VARCHAR(64),
    business_key   VARCHAR(128),
    action         VARCHAR(16),              -- CREATE UPDATE DELETE NOOP
    direction      VARCHAR(16),              -- SIS_TO_LMS | LMS_TO_SIS
    endpoint       VARCHAR(256),
    http_status    INT,
    attempt        INT,
    duration_ms    BIGINT,
    status         VARCHAR(24),
    message        VARCHAR(1024),
    logged_at      TIMESTAMP    NOT NULL
);

CREATE INDEX ix_log_event  ON integration_log (event_id);
CREATE INDEX ix_log_time   ON integration_log (logged_at);

-- ---------------------------------------------------------------------
-- 6. dead_letter — loi du lieu can ra soat thu cong (NFR-03).
--    Loi KHONG bi nuot: luon co the dua lai vao hang doi tu trang quan tri.
-- ---------------------------------------------------------------------
CREATE TABLE dead_letter (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbox_event_id  BIGINT       NOT NULL,
    reason          VARCHAR(1024),
    created_at      TIMESTAMP    NOT NULL,
    CONSTRAINT fk_dead_letter_inbox FOREIGN KEY (inbox_event_id) REFERENCES inbox_event (id)
);
